### PR TITLE
Add ability to search functions

### PR DESCRIPTION
**Pull request by johnletey**
@nikitavoloboev It works when I run `alias-search -p ~/.dotfiles/zsh/functions functions`

I'm not going to be able to work on anything until Monday, but go ahead and take a look

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
Thanks, will take a look

**Comment by johnletey** [comment]
@nikitavoloboev How does this look?

**Comment by nikitavoloboev** [comment]
It's perfect 🎊

**Comment by johnletey** [comment]
Awesome!

**Pull request merged**
