### PR TITLE
Ability to scan through user aliases

### PR DESCRIPTION
**Pull request by johnletey**
@nikitavoloboev Here's my rough draft

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
```bash
~/.dotfiles master*
❯ alias-search -p zsh
usage: alias-search [<flags>] <command> [<args> ...]

Search aliases and commands

Flags:
      --help      Show context-sensitive help (also try --help-long and --help-man).
      --version   Show application version.
  -p, --path="."  The provided directory to scan for functions and aliases.

Commands:
  help [<command>...]
    Show help.

  functions
    Scans .zsh files for functions.

  aliases
    Saves all aliases from .zsh files.



~/.dotfiles master*
❯ d zsh

~/.dotfiles/zsh master*
❯ a
alias.zsh  bindings.zsh  env.zsh  functions  options.zsh  plugins.txt  zprofile.zsh  zshrc.zsh

~/.dotfiles/zsh master*
❯ alias-search -p .
usage: alias-search [<flags>] <command> [<args> ...]

Search aliases and commands

Flags:
      --help      Show context-sensitive help (also try --help-long and --help-man).
      --version   Show application version.
  -p, --path="."  The provided directory to scan for functions and aliases.

Commands:
  help [<command>...]
    Show help.

  functions
    Scans .zsh files for functions.

  aliases
    Saves all aliases from .zsh files.



~/.dotfiles/zsh master*
❯
```

Just tried it out. What am I doing wrong.

**Comment by nikitavoloboev** [comment]
Btw the end goal of the tool is to have some config file where you specify which directories contain your dotfiles or pinpoint specific files you want to search over.

The the tools scans those files/dirs, makes an index of aliases/functions with comments it can find.

And the user can via [fzf](https://github.com/junegunn/fzf) search through the command/comment to paste/run the command in his current shell.

**Comment by johnletey** [comment]
You need to run `alias-search -p . aliases` to output all of the aliases that you have

**Comment by nikitavoloboev** [comment]
```bash
❯ alias-search -p ~/.dotfiles/zsh aliases
[/Users/nikivi/.dotfiles/zsh/alias.zsh /Users/nikivi/.dotfiles/zsh/bindings.zsh /Users/nikivi/.dotfiles/zsh/env.zsh /Users/nikivi/.dotfiles/zsh/options.zsh /Users/nikivi/.dotfiles/zsh/zprofile.zsh /Users/nikivi/.dotfiles/zsh/zshrc.zsh]
map[Names:[nr n nq nQ nuu te op dnd g peek aet crypto lc rw mr _ ae le wifi eo es mc pd yt r e s ss alf ta d lg so ka rl how ua sudo m jj mm ma rec dus to t zo ff ki icat tt tre q screen ad mx rr a aa wg v os lt tp ll jd tm rf ser cra lic p p2 wf wfl wfa ws c k kl kf kde ke kg ks kd ksw kp nd ndi n. i ii ig iir iis in ia ir ire is dev o org og. ot or oo ov ogu ob ora oe ugo rb h2 h10 t10 hs cwd rrpdf sz us ut u ngup ngdown ngre nglog ngerr cpu mem bb xx x. we ww zr pdf ee ei egi ej ew essh ek ez dw ds dk dsh dn di dg dl dv dm da dr dla dz de dq dls drp dbin dx dxi dxm d.. db dh gto gj gm ger grl grhf glo gfk gsp gu gdp ggh gre gq gqa gb gr grc ggn g: ggf g:: gi gl gn g. ga gg glp grao greset gd gds gdn gs gss] Commands:[nix repl nix-env nix-env -q | fzf | xargs -I{} nix-env -e {} nix-env -q nix-env -u tree open do-not-disturb toggle git tee >(cat 1>&2) subl CONTRIBUTING.md curl rate.sx tokei open -a "Marked 2" README.md open -a "Marked 2" sudo subl README.md less -r wifi-password -q echo elasticsearch md-to-alfred pandoc yotube-dl rg nvim subl subl . alfred touch readme.md cd ls | grep source echo curl howdoi unalias sudo  mkdir killall tmux tldr man asciinema rec du -s touch bat open open . kill imgcat tldr tree -a exit screenfetch open . chmod +x rm -rf exa exa -la wget -r --no-parent mv osascript ls -lart type ln -s jid task reflex serve npx create-react-app legit python python2 alfred build alfred link alfred pack -o ~/Desktop workflow-install -s workflow docker kubectl kubectl logs kubectl logs -f kubectl describe kubectl explain kubectl get kubectl get pods kubectl delete pods kubectl get pods -o=wide -w kubectl port-forward node node install node . npm npm install npm install -g npm install && npm run dev npm install && npm start npm init npm add npm run npm remove npm start npm run dev go richgo go get ./... playgo go run go install go vet go get -u go build go-pry go build -o main Go-Package-Store ruby head -n 2 head -n 10 tail -n 10 ghci pwd | pbcopy rm -rf *.pdf exec zsh hugo server -D hugo server -w hugo sudo nginx sudo nginx -s stop sudo nginx -s stop && sudo nginx tail -f /usr/local/var/log/nginx/access.log tail -f /usr/local/var/log/nginx/error.log top -o cpu top -o rsize pbcopy open -a Xcode open -a Xcode . code code . open -a Preview open -a PDF\ Expert nvim . nvim index.js nvim .gitignore nvim package.json nvim ~/.dotfiles/nvim/init.vim nvim ~/.ssh/config nvim ~/.dotfiles/karabiner/karabiner.edn nvim ~/.zshrc cd ~/Documents/ cd ~/src/ideas cd ~/Dropbox/Write/knowledge cd ~/.ssh cd ~/src/clones cd ~/src/nix cd ~/go/src/github.com/nikitavoloboev cd ~/src/build-to-learn cd ~/src/test cd ~/src/games cd ~/src/ cd ~/src/alfred cd ~/src/orgs/learn-anything cd ~/.dotfiles cd ~/Desktop cd ~/Downloads cd ~/Library/Services cd ~/Dropbox cd /usr/local/bin/ cd ~/src/Xcode cd ~/src/Xcode/iOS cd ~/src/xcode/macOS cd ~/.config cd ~/.dotfiles/bin cd ~/.hammerspoon gittower open `git config remote.origin.url` git branch -m git checkout - git reset --hard && git clean -df git checkout HEAD -- git log --pretty=oneline --abbrev-commit --graph --decorate git fetch && git reset --hard && git clean -dfx git pull --rebase --autostash git issues git reset --hard HEAD~; git push --force-with-lease push -u origin HEAD git rebase -i HEAD~4 git stash git stash apply git checkout -b git reset --hard git rm --cached git_add_origin_and_origin_push git push -u origin master git push -f git_remote_add_origin_from_active_link git init git pull git clone git add . git add git push git pull && git push git remote add origin git reset --soft HEAD^ git diff git diff --staged git diff --name-only git status --short git show --word-diff=color] Descriptions:[  Search installed packages to uninstall See installed packages Upgrade packages    Wrapper over git Mirror stdout to stderr, useful for seeing data going through a pipe  Get crypto prices     Edit readme file                                          See hidden files                  Symlink `source` directory    Get logs for <pod> streaming in real time                        go get all packages for current project     use the network to update the named packages and their dependencies    displays updates to Go packages          testing     TODO: maybe wrong location   # CPU Memory        Current dir  TODO: make it zsh func, go to root and then run it  nvimrc ssh config                              Rename current branch Checkout last branch you were on Reset to exact state as last commit Git reset single file  Reset repo to clean remote state Git stash, pull and apply stash  Delete previous commit locally and remote                         See changes made]]

~
❯

```

Result I got. A bit messy but I guess we can work from that?

**Comment by nikitavoloboev** [comment]
I was thinking more of a hash map of [command : comment] where comment is optional.

And then we can search over that.

**Comment by johnletey** [comment]
> A bit messy

Yes I agree

> I was thinking more of a hash map of [command : comment] where comment is optional.

I'll try to do this real quick

**Comment by nikitavoloboev** [comment]
> I'll try to do this real quick

Can test it on https://github.com/nikitavoloboev/dotfiles/tree/master/zsh if you like. Or your own aliases/functions if you got those.

**Comment by johnletey** [comment]
@nikitavoloboev By the way, what do you mean by `command`? Do you mean the name of the alias or the actual command?

**Comment by johnletey** [comment]
> Can test it on https://github.com/nikitavoloboev/dotfiles/tree/master/zsh if you like. Or your own aliases/functions if you got those.

I'll test it on yours, as mine are extremely messy!

**Comment by nikitavoloboev** [comment]
> name of the alias or the actual command?

Good point. So for functions it's simple [function-name : comment].

For aliases. I think we should include [alias-name : comment].

But we could also do [real-command : comment] 

Or maybe even better include all 3:

[alias : comment : real-command]

What do you think?

**Comment by johnletey** [comment]
> What do you think?

IMO `[alias : comment : real-command]`

**Comment by nikitavoloboev** [comment]
Let's do that

**Comment by nikitavoloboev** [comment]
A side note, but when we build this tool, I was thinking of building an external file where I annotate commands I have on my system with some comment. Something that won't even be sourced by `zsh` but can be used by this tool to increase it's DB/index with annotated commands.

**Comment by nikitavoloboev** [comment]
Perhaps a YAML file or even .csv:

`
man,search man pages
ls, list directories
`

etc..

**Comment by johnletey** [comment]
@nikitavoloboev It's kind of hard to do a map with `[alias : comment : real-command]`

Do you know of any nice way to do this?

In the mean time, I'm pushing some working code for `[real-command : comment]`

**Comment by johnletey** [comment]
> Something that won't even be sourced by `zsh` but can be used by this tool to increase it's DB/index with annotated commands.

So you want to generate descriptions for the `real-command`'s if there aren't any already?

> Perhaps a YAML file or even .csv

Let's use a YAML file since I've heard that they're really nice. Although, if I'm being honest, I haven't coded in Go that much (or used YAML files), but I'm up for the challenge.

**Comment by nikitavoloboev** [comment]
> It's kind of hard to do a map

It won't be a map as maps are two way from my knowledge. Just map it like [alias : real-command + comment] where `+` is some separator. 

This way we get all the info we need to search over and on return, we print out the `alias` to the shell or execute it immediately depending on some flag. Say add flag `-f` which indicate execute alias/function and by default just print out the alias/function to shell with space added so user can fill out arguments to the thing.

**Comment by nikitavoloboev** [comment]
> So you want to generate descriptions for the `real-command`'s if there aren't any already?

Yeah. Basically annotate in the same way as we do aliases/functions, other tools in user's path.

Perhaps we can automate it and use something like [Explain Shell](https://explainshell.com) or have a community default set of tools already annotated with possibility to custom extend the list with tools that are not 'default'.

I'll open an issue for this so we discuss it there.

**Comment by johnletey** [comment]
I feel like the extent of this PR has been met in the latest commit ... but all of the useful comments should be taken and make into their on issues for future PRs

**Comment by nikitavoloboev** [comment]
> all of the useful comments should be taken and make into their on issues for future PRs

Should I open the issues or you want to do that?

**Comment by nikitavoloboev** [comment]
Taking a look at PR now

**Comment by nikitavoloboev** [comment]
Looks amazing. Really good job @johnletey 🎊

**Comment by nikitavoloboev** [comment]
Ill open the issues :)

**Comment by johnletey** [comment]
> Ill open the issues :)

Thank you so much! Much appreciated

**Comment by nikitavoloboev** [comment]
Done. If I missed something, feel free to open more issues.

**Comment by johnletey** [comment]
> If I missed something, feel free to open more issues.

Will do! Looks great so far

**Pull request merged**
